;;; -*- lexical-binding: t; -*-
(provide 'prettify-redex-alist)
(require 'prettify-utils)
(defvar prettify-redex-alist
  (prettify-utils-generate
   ("|>"		"▷")
   ("<|"		"◁")
   ("->>"		"↠")
   ("->"		"→")
   ("<-"		"←")
   ("=>"		"⇒")
   ("<="		"⇐")
   ("|->"   "↦")
   ("tau"   "τ") ("tau_1" "τ₁") ("tau_2" "τ₂") ("tau_3" "τ₃") ("tau_4" "τ₄")
   ("e" "e") ("e_1" "e₁") ("e_2" "e₂") ("e_3" "e₃") ("e_4" "e₄")
   ("i" "i") ("i_1" "i₁") ("i_2" "i₂") ("i_3" "i₃") ("i_4" "i₄")
   ("x" "x") ("x_1" "x₁") ("x_2" "x₂") ("x_3" "x₃") ("x_4" "x₄")
   ("v" "v") ("v_1" "v₁") ("v_2" "v₂") ("v_3" "v₃") ("v_4" "v₄")
   ("any" "U") ("any_1" "U₁") ("any_2" "U₂") ("any_3" "U₃") ("any_4" "U₄") ("any_4" "any₅")
   ("any_!_1" "U!₁") ("any_!_2" "U!₂") ("any_!_3" "U!₃") ("any_!_4" "U!₄")
   ("dot" "·") ("hole" "[·]")
   ("comma" ",")
   ("Gamma" "Γ")
   ("gamma" "γ")
   ("psi" "ψ")
   ("Psi" "Ψ")
   ("lambda" "λ")
   ("Lambda" "Λ")
   ("doublecomma" "„")
   ("forall" "∀")
   ("empty" "Ø")
   ("alpha" "α")
   ("number" "ℕ") ("number_1" "ℕ₁") ("number_2" "ℕ₂")
   ("|-"  "⊢")
   ;; ("-->" "⟶")
   ))
